# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Miele@Home-Anbindung'
        en: 'Connect Miele@Home'
    maintainer: sipple, AndreK01
#    tester:                         # Who tests this plugin?
    state: develop                   # change to ready when done with development
    keywords: iot Miele Home 
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1512798-miele-home-mit-mqtt

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.5              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: true
    classname: mieleathome             # class containing the plugin

parameters: 
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    miele_cycle:
        type: int
        default: 300
        description:
            de: 'Zeitlicher Abstand zwischen zwei Verbindungen zur API'
            en: 'Time between two connects to the API'
    miele_client_id:
        type: str
        default: ''
        description:
            de: 'Client ID der Miele API'
            en: 'Client ID for the Miele-API'
    miele_client_secret:
        type: str
        default: ''
        description:
            de: 'Client Secret der Miele API'
            en: 'Client secret for the Miele-API'
    miele_client_country:
        type: str
        default: 'de-DE'
        description:
            de: 'Länderkennung der Miele-API'
            en: 'Counry to use for the Miele-API'
    miele_user:
        type: str
        default: ''
        description:
            de: 'Zugangsdaten User'
            en: 'Credentials User'
    miele_pwd:
        type: str
        default: ''
        description:
            de: 'Zugangsdaten Passwort'
            en: 'Credentials password'            

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    miele_deviceid:
        type: str
        mandatory: False
        description:
            de: 'Die DeviceId der Miele-cloud'
            en: 'deviceId of the Miele-cloud'
    miele_command:
        type: dict
        mandatory: False
        description:
            de: 'Eine interne Funktion des Miele@Home-Plugins'
            en: 'internal function of the Miele@Home-Plugin'
    miele_visu_function:
        type: str
        mandatory: False
        description:
            de: 'Eine interne Funktion des Miele@Home-Plugins'
            en: 'internal function of the Miele@Home-Plugin'
item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)
    child:
        name: Vorlage Struktur Miele Geräte
        ident:
            device_type:
                value_raw:
                   type: num
                   cache: 'on'
                value_localized:
                    type: str
                    cache: 'on'
            deviceName:
                type: str
                cache: 'on'
            deviceIdentLabel:
                fabNumber:
                    type: str
                    cache: 'on'
                fabIndex:
                    type: str
                    cache: 'on'
                techType:
                    type: str
                    cache: 'on'
                matNumber:
                    type: str
                    cache: 'on'                   
            xkmIdentLabel:
                techType:
                    type: str
                    cache: 'on'
                releaseVersion:
                    type: str
                    cache: 'on'
        state:
            ProgramID:
                value_localized:
                    type: str
                    cache: 'on'
            status:
                value_localized:
                    type: str
                    cache: 'on'
            programType:
                value_localized:
                    type: str
                    cache: 'on'
            programPhase:
                value_localized:
                    type: str
                    cache: 'on'                                                                                
            remainingTime:
                type: list
                cache: 'on'
            startTime:
                type: list
                cache: 'on'          
            targetTemperature:
                value_localized:
                    type: num
                    cache: 'on'             
                unit:
                    type: str
                    cache: 'on'
            temperature:
                value_localized:
                    type: num
                    cache: 'on'             
                unit:
                    type: str
                    cache: 'on'                    
            signalInfo:
                type: bool
                cache: 'on'
            signalFailure:
                type: bool
                cache: 'on'
            signalDoor:
                type: bool
                cache: 'on' 
            dryingStep:
                value_localized:
                    type: str
                    cache: 'on'             
                value_raw:
                    type: num
                    cache: 'on'                                            
            elapsedTime:
                type: list
                cache: 'on'                          
            ecoFeedback:
                currentWaterConsumption:
                    unit:
                        type: str
                        cache: 'on'
                    value:
                        type: num
                        cache: 'on'
                currentEnergyConsumption:
                    unit:
                        type: str
                        cache: 'on'
                    value:
                        type: num
                        cache: 'on'
                waterForecast:
                    type: num
                    cache: 'on'
                energyForecast:
                    type: num
                    cache: 'on'                    
            batteryLevel:
                type: num
                cache: 'on'
                
                    
        visu:
            charging_time:
                type: num
                visu_acl: rw
                cache: 'on'
                database: 'yes'                
#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions:
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters:
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
